<a href="https://colab.research.google.com/github/cherryWood55/Assignment-2/blob/master/MLCCNumpy_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Examples

## What is numpy?

#### Python has built-in:

-  containers: lists (costless insertion and append), dictionaries (fast lookup)
-  high-level number objects: integers, floating point

#### Numpy is:

 - extension package to Python for multidimensional arrays
 - closer to hardware (efficiency)
 - designed for scientific computation (convenience)


#### Import numpy



In [0]:
import numpy as np

### Uncomment Print statement and run each cell to see the output

#### Create numpy arrays


In [6]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(a)
print(type(a)) #print type of a

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print (b)
print(type(b))              #print type of b
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
1 2 4


#### Some basic functions for creating arrays. Print all the defined arrays and see the results.

In [18]:
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(3)
d = np.full(shape=(5,4), fill_value=5)
e = np.random.random((2,2))

print('a', a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
d [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
e [[0.37649273 0.51193667]
 [0.75305213 0.44621056]]


#### Execute and understand :)

In [25]:
a  =  np.arange(10)
b  =  np.linspace(0,10, num=8)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]


#### Array Indexing

In [28]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

print(a[0, 1])   # Prints "2"

b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"
print (a)

2
77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
#Whereas this is not the case with lists
a = [1,2,3,4,5,6,7,8,9,10,11,12]
b = a[:]
b[0] = 77
print (a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


#### Slicing

In [32]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


#### Aritmetic operations

In [36]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


#### Using Boolean Mask

In [39]:
b = np.arange(10)

print(b)

mask = b%2!=0 #perform computations on the list 

print(mask)

print(b[mask]) #applying the mask on the numpy array


[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [41]:
modified_b = b
modified_b[mask] = -1

print(modified_b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Swapping two columns in a 2d numpy array

In [49]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


#### Swapping two rows in a 2d numpy array

In [47]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[[1,0,2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


***A summary of the knowledge about Numpy I take back: ***

*   `a = np.array([1,2,3,4,5])` creates a numpy array of 1 dimension (rank)

*   a.shape() gives the shape of the array in the following format(row, column)

*   `np.ones(shape=(3,2))` gives an array of 3 rows and 2 columns containing all entries as 1 (Similarly, `np.zeroes(shape=(3,2))`)

*   `np.full(shape=(3,2), fill_value = 9)` gives an array of 3 rows and 2 columns conatining all entries equal to the fill_value

*   `np.eye(3)` gives a unit matrix of given shape

*   `np.random.random((3,3))` gives an array containing all random values

*   `np.arange(10)` gives a 1-D array containing integer entries from 0 to 9

*  `np.linspace(0, 10, num = 5,endpoint = True)` gives an array containing 'num' evenly spaced values between 0 and 10. If endpoint is True, 10 is included else it is excluded

*  ` a = np.array([1,2,3,4], [5,6,7,8]) `
is a 2-D array of shape (2,4). Now if we create a slice of the array a and store in b, say `b = a[:, 1:3]` and then modify the contents of b, then the changes will be reflected in a as well. This is because the slice of an array is a view into the actual array. (This is not the same with lists)

*  We can slice the 2-D arrays like `b = a[1:, 2:4]` as well as `b = a[1:2, 2:4]`. The first one is a Rank 1 view and the second one is a Rank 2 view of the slice

* `np.sum(a)` gives the sum of all the elements of a. If the axis is mentioned, as in, axis=0, the sum of the columns is calculated, and axis=1, the sum of the rows is calculated

* Mask is a condition applied on the array, applying the mask on the array separates out only those elements which satisfy the condition specified

* We can also get the whole array with the elements of the mask being displayed in a different manner (like, assign -1 to all those values which fulfilled the condition)
 
* We can swap the elements of particular rows and columns of an array just like we sliced an array, just mention the positions where the indices are to be placed









