<a href="https://colab.research.google.com/github/cherryWood55/Assignment-2/blob/master/MLCCNumpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [27]:
import numpy as np #import numpy
a = np.linspace(-1.3, 2.5, num = 64)
print (a)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

`np.resize(array_name, num) ` gives you a cyclic pattern of the array repeated 'num' times

In [6]:
n = int(input())
b = np.array([1,2,3])
b_modified = np.resize(b, 3*n)
print (b_modified)

4
[1 2 3 1 2 3 1 2 3 1 2 3]


3) Create an array of the first 10 odd integers.

`np.arange(start, stop, step)` takes an optional argument which increments start by that step and ends just before stop

In [5]:
c = np.arange(1,20,2)
print (c)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

`np.intersect1d(a,b)` gives the unique and common values between two arrays a and b

In [8]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
res = np.intersect1d(a, b)
print (res)

[2 4]


5) Reshape 1d array a to 2d array of 2X5

np.reshape(array_name, (shape)) takes two arguments -  an array to which the operation is to be performed and the shape to which the array will be shaped

In [12]:
a = np.arange(10)
a_modified = np.reshape(a,(2,5))
print (a_modified)

[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

np.asarray(list_argument) converts a list to a numpy array

In [15]:
#Convert list to numpy array
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
array1 = np.asarray(list1)
print (array1)
print (type(array1))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


np.ndarray.tolist(array_argument) converts a numpy array to a list

In [18]:
#Convert numpy array to list
list2  = np.ndarray.tolist(array1)
print (list2)
print (type(list2))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

np.pad(array_name, pad_width = depth_of_the_border, mode='constant', constant_values = fill_value) 
gives a border or a pad around an array of depth equal to pad_width filled with values equal to constant_values

In [36]:
a = np.zeros(shape=(10,10), dtype='int')
a = np.pad(a, pad_width=1, mode='constant', constant_values=1)
print (a)

[[1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

a[start:stop] denotes a slice of the array a
it can take a third optional argument which denotes the step with which it elements are chosen from the array
a[start:stop:stride] starts taking values from 'start' till 'stop',moving forward by 'stride' steps

In [34]:
a = np.zeros(shape = (8,8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print (a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
